version: '3.9'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: greenacademy
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: gunicorn --config gunicorn.conf.py green_academy.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: green_academy.settings
      DATABASE_URL: postgresql://admin:password@db:5432/greenacademy
      SECRET_KEY: your-secret-key
      DEBUG: "False"
      ALLOWED_HOSTS: "yourdomain.com,127.0.0.1"
      CORS_ALLOWED_ORIGINS: "http://localhost:3000,https://yourfrontend.com"

volumes:
  postgres_data:
